### ISSUE TITLE
config.json issues [v5.0.0-beta.6]

### ISSUE THREAD

**Issue by elf-pavlik** [solid/node-solid-server#1081]
I have encountered some issues with `config.json`

1. `solid init` doesn't save `serverUri` to `config.json`
2. setting `"multiuser": true` & `"webid": false` results in
```
  solid:get / on idp.hackers4peace.net +3s
  solid:get GET -- Error: 404 Can't find file requested: [object Object] +2ms
```
3. setting `"multiuser": false` and  `"webid": false` results in
```
  solid:get / on idp.hackers4peace.net +7ms
  solid:get    sending data browser file: /usr/lib/node_modules/solid-server/static/databrowser.html +31ms
```
4. setting `"multiuser": false` and `"webid": true` and `"auth": "oidc"` finally leads to expected
![screenshot_2019-01-31 welcome to solid](https://user-images.githubusercontent.com/876431/52076511-71e7ad80-2554-11e9-8ac5-956be9cc7c54.png)

I plan to use this deployment only as OIDC Issuer for external WebIDs, it will never act as Resource Server. Another deployment on different domain will act as Resource Server which will also include WebID Profile, but will not act as OIDC Issuer. Currently both don't require `"multiuser": true`, but later I might enable it.

I miss combination of configuration options to clearly define:
* only act as OIDC Issuer, no Resource Server
* only act as Resource Server, no OIDC Issuer

I would also like to disable WebID-TLS on those both servers, only using WebID-OIDC.

Related to #672

**Comment by megoth** [comment]
#1 is also reported in https://github.com/solid/node-solid-server/issues/1021.

I think we should prioritize these bugs.

**Comment by elf-pavlik** [comment]
Yes, also `#2` looks like a bug. The rest maybe just needs better documentation on what those options affect, including how it affects what will get served from `${serverUri}/`

**Comment by megoth** [comment]
It seems that `webId: false` is simply a configuration that hasn't gotten any love in a long time. Especially when setting up a brand new server with that configuration. This bug is also in NSS4.4.1, so we'll remove the regression label on this. This is also a use case we should probably take a step back, have a good think and do more research, and make sure that we support it properly, so we'll drop the prioritization wrt v5.0.0.

It could be that it's simply a case of better documentation, but again, I want to go about this properly. I'll give it a high priority so that we'll quickly get back at it after the release of v5.0.0.

**Comment by jaxoncreed** [comment]
Most of this seems to have been fixed except for multiuser: true and webid: false. It now throws an error in that case because you cannot have users without a webid
