### ISSUE TITLE
Paths for new resources are incorrectly generated by LDP POST

### ISSUE THREAD

**Issue by Otto-AA** [solid/node-solid-server#1228]
When trying to create a new folder via the solid-filemanager I get a `500 - Path must start with hostname (/otman.inrupt.net)` with the new version on inrupt.net

I've made a POST to https://otman.inrupt.net/public with `slug: my-folder`, `link: <http://www.w3.org/ns/ldp#BasicContainer>; rel="type"` and `Content-Type: text/turtle`.
It responded with the status 500 and the statusText `Path must start with hostname (/otman.inrupt.net)`.

Is this something we should change in the request setup or an error inside NSS?

Here are the complete request headers (except for bearer token and connect.sid cookie):
```
POST /public HTTP/1.1
Host: otman.inrupt.net
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:67.0) Gecko/20100101 Firefox/67.0
Accept: */*
Accept-Language: en,en-US;q=0.7,de;q=0.3
Accept-Encoding: gzip, deflate, br
link: <http://www.w3.org/ns/ldp#BasicContainer>; rel="type"
slug: my-folder
Content-Type: text/turtle
authorization: Bearer  {...}
Origin: https://solid-filemanager.solid.community
Content-Length: 0
DNT: 1
Connection: keep-alive
Referer: https://solid-filemanager.solid.community/public/nightly/?url=https://otman.inrupt.net/public
Cookie: connect.sid=s%3 { ... }
Pragma: no-cache
Cache-Control: no-cache
```

And the response headers:
```
HTTP/1.1 500 Internal Server Error
X-Powered-By: solid-server/5.1.5
Access-Control-Allow-Origin: https://solid-filemanager.solid.community
Vary: Accept, Authorization, Origin
Access-Control-Allow-Credentials: true
Access-Control-Expose-Headers: Authorization, User, Location, Link, Vary, Last-Modified, ETag, Accept-Patch, Accept-Post, Updates-Via, Allow, WAC-Allow, Content-Length, WWW-Authenticate
Allow: OPTIONS, HEAD, GET, PATCH, POST, PUT, DELETE
Link: <public.acl>; rel="acl", <public.meta>; rel="describedBy", <http://www.w3.org/ns/ldp#Resource>; rel="type"
Content-Type: text/plain; charset=utf-8
Content-Length: 50
ETag: W/"32-fmcIjz1GGt/H6AvpCi6o3nXP7kw"
Set-Cookie: connect.sid=s%3 {...}; Domain=.inrupt.net; Path=/; Expires=Sun, 16 Jun 2019 05:44:04 GMT; HttpOnly; Secure
Date: Sat, 15 Jun 2019 05:44:04 GMT
Connection: keep-alive
```

**Comment by jaxoncreed** [comment]
I believe I know what's causing this @Otto-AA . This is probably a good first issue to get involved with the Node Solid Server maintenance team.

If you're interested, I'd love to hop on a call with you so we can fix it together!

**Comment by Otto-AA** [comment]
I would really love to get more involved into this project, but I am too occupied by other projects and work currently. Therefore I have to gratefully decline your offer for now. If I find more time in the future I will maybe come back to this project though.

**Comment by michielbdejong** [comment]
Was able to reproduce this on dev.inrupt.net with:
```sh
curl 'https://michielbdejong.dev.inrupt.net/public/' -H 'Cookie: connect.sid=...' -H 'slug: my-folder' -X 'POST'
```
(you can get a valid cookie by logging in to the data browser, going to the network pane in the dev tools, and selecting 'copy as curl' on one of the xhr requests)

**Comment by michielbdejong** [comment]
In fact it also happens if you leave out the `-H 'slug: my-folder'`

**Comment by michielbdejong** [comment]
@RubenVerborgh could this have been caused your recent refactor?

**Comment by RubenVerborgh** [comment]
No refactor happened, but yes, a fix for one bug was added (https://github.com/solid/node-solid-server/pull/1227).

The fix itself is probably not faulty; rather, the code calling this function was (and has always been) at fault, but it went undetected before the fix. Would need a stack trace to pinpoint.

**Comment by michielbdejong** [comment]
> No refactor happened

I was referring to the ResourceMapper refactor (#1213), which we know also caused the bug that #1227 fixed.

> Would need a stack trace to pinpoint.

The following suggests this is indeed a problem with the ResourceMapper:
```sh
~/gh/solid/node-solid-server $ grep -r Path\ must\ start\ with\ hostname lib/
lib//resource-mapper.js:        throw new Error(`Path must start with hostname (/${hostname})`)
```

To reproduce on localhost, run in multi-user mode (need to run `./bin/solid-test init`), start the server, then visit https://localhost:8443, register a user, for instance 'michielbdejong', add e.g. '127.0.0.1 michielbdejong.localhost' in your /etc/hosts, then do:
```sh
~/gh/solid/node-solid-server $ curl -k -X POST https://michielbdejong.localhost:8443/inbox/
Path must start with hostname (/michielbdejong.localhost)
```

**Comment by michielbdejong** [comment]
Maybe we should just revert to the code from before #1213?

**Comment by RubenVerborgh** [comment]
No. See above answer.

> The following suggests this is indeed a problem with the ResourceMapper:

It shows that the error is thrown by ResourceMapper. ResourceMapper will correctly throw that error when called with the wrong arguments. Hence my request for a stack trace.

**Comment by michielbdejong** [comment]
```sh
  solid:server Error page because of: Error: Path must start with hostname (/michielbdejong.localhost)
    at ResourceMapper.mapFileToUrl (/Users/michiel/gh/solid/node-solid-server/lib/resource-mapper.js:74:15)
    at LDP.post (/Users/michiel/gh/solid/node-solid-server/lib/ldp.js:157:68) +1ms

**Comment by michielbdejong** [comment]
`lib/ldp.js` is [calling](https://github.com/solid/node-solid-server/blob/master/lib/ldp.js#L157)  `this.resourceMapper.mapFileToUrl` with:
```js
{
  resourcePath: '/inbox/afaf3830-9355-11e9-850a-2f6182efecf6',
  host: 'michielbdejong.localhost'
}
```

**Comment by michielbdejong** [comment]
The ["do not expose root path"](https://github.com/solid/node-solid-server/commit/272adef893dff9eb835513dca5b9a5d7786b06b7#diff-4b9b8e50857ade6dd5db969387fe5f20R157) refactor changed that `resourcePath` value there from
`this.resourceMapper.rootPath + resourcePath` to just `resourcePath`, so looks like that's triggering the 'Path must start with hostname' error.

**Comment by RubenVerborgh** [comment]
> The ["do not expose root path"](https://github.com/solid/node-solid-server/commit/272adef893dff9eb835513dca5b9a5d7786b06b7#diff-4b9b8e50857ade6dd5db969387fe5f20R157) refactor changed that `resourcePath` value there from
> `this.resourceMapper.rootPath + resourcePath` to just `resourcePath`, so looks like that's triggering the 'Path must start with hostname' error.

Indeed. And in doing so, it is catching an error that was present in the original code, but went unnoticed. So the error it's doing its job 🙂

Historical note: `ResouceMapper` was introduced a year ago, as a way to finally have all knowledge about URL/filesystem correspondence in one place, as a solution to it being implemented 20 times in 10 different and incompatible ways.
However, `ResourceMapper` was then extended to leak its abstraction, such that the supposedly internal knowledge was once again spreading through the code. #1213 restored the original intention.

Now the change from `this.resourceMapper.rootPath + resourcePath` to `resourcePath` was correct (given the updated method): the (semantically) equivalent parameters are ultimately passed to the method. It is just that the original code was wrong in the first place, but this went unnoticed because there was no path correctness check—and now there is.

Let me show where it goes wrong:
`this.resourceMapper.rootPath + resourcePath` will result in `/var/solid/data` + `/inbox/afaf3830-9355-11e9-850a-2f6182efecf6` and thus `/var/solid/data/inbox/afaf3830-9355-11e9-850a-2f6182efecf6` instead of the correct (assuming multi-user mode) `/var/solid/data/michielbdejong.localhost/inbox/afaf3830-9355-11e9-850a-2f6182efecf6`. This is precisely the error that is being thrown now, as opposed to going silent.

So if this code was actually used as above, then I expect to see lots of random folders under `/var/solid/data` on different servers (if `mkdir -p` was ultimately used); and/or a privilege escalation security bug where people could write to random people's folders by sending a `POST` to `/michielbdejong.localhost/inbox/afaf3830-9355-11e9-850a-2f6182efecf6` (let's hope this did not happen).

All of the above showing why _one_ component and one component only should implement file to URL mapping.

Now the question, how to fix this bug?

Looking at [the code](https://github.com/solid/node-solid-server/blame/5ba2c314f4c9a0bf6aaea8ea795eb2c165dcec07/lib/ldp.js#L157) it seems that the call to `mapFileToUrl` is wrong to begin with, because there never was a file in the first place. Instead, it should probably be something like `url.resolve(container, resourcePath)` (assuming here that `container` is the URL of the container, not sure).

**Comment by RubenVerborgh** [comment]
(Not to mention that the `contentType` hack is terrible too.)

**Comment by RubenVerborgh** [comment]
(Not to mention that the `contentType` hack is terrible too.)

**Comment by RubenVerborgh** [comment]
@jaxoncreed Key to getting this right will be clearly differentiating between what is a _file_ path (naming suggestion: end with `path`, do unsure if properly applied in existing code), and what is a _URL_. Code should either `path.resolve` files against existing folders, `url.resolve` URLs against existing URLs, or take _absolute_ file paths or URLs and pass them to `ResourceMapper`. All else will lead to bugs.

**Comment by jaxoncreed** [comment]
This should be fixed

**Comment by highlevellogic** [comment]
Related. I just got a pod server set-up - v5.5.2
When the registration processed is finished, it automatically sends me to my page.
(from https://solid.example.com/register to https://rogerfgay.solid.example.com/)
Then I get the error message in the browser and nothing else. 

Path must start with hostname (/rogerfgay.solid.example.com)

Server-side:
  solid:get / on rogerfgay.solid.example.com +0ms
  solid:get GET -- Error: undefined Path must start with hostname (/rogerfgay.solid.example.com) +1ms
  solid:server Error page because of: Error: Path must start with hostname (/rogerfgay.solid.example.com)
    at ResourceMapper.mapFileToUrl (C:\Users\roger\AppData\Roaming\npm\node_modules\solid-server\lib\resource-mapper.js:77:15)
    at LDP.get (C:\Users\roger\AppData\Roaming\npm\node_modules\solid-server\lib\ldp.js:358:10)
