### ISSUE TITLE
Mail command failed: 501 mail from address must be same as authorization user

### ISSUE THREAD

**Issue by yzs15** [solid/node-solid-server#1281]
## Please describe what you did in reproducible steps
I set up an email service using qq.com (an email service provider in China).  when I tried to reset my password, ERROR "Mail command failed: 501 mail from address must be same as authorization user" raised. 
Below is the configure of my node server.
![image](https://user-images.githubusercontent.com/31000394/62469942-e1707b00-b7cb-11e9-9c78-df925343ef6f.png)

**Comment by michielbdejong** [comment]
Hi @yzs15,

It looks like this issue is related to qq.com and the value of your 'emailAuthUser' there. Try changing that config value from 'yuzish96@qq.com' to just 'yuzish96'? If that doesn't work, then please check out any developer forums or tech support qq.com might have.

Please reopen this issue if you think it's an issue with NSS instead, but I do need to give a heads-up, we're in the middle of a switch from this code to https://github.com/inrupt/pod-server, which is the TypeScript rewrite of this server, so probably it's better if you try running that server instead of this one! Let me know if I can help with that.

HTH!
