### ISSUE TITLE
Sharing pane broken on inrupt.net

### ISSUE THREAD

**Issue by rubensworks** [solid/node-solid-server#1286]
The sharing pane for any app or file seems to be not working,
as can be seen in the screenshot below.

<img width="1270" alt="Screen Shot 2019-08-12 at 09 27 16" src="https://user-images.githubusercontent.com/440384/62850597-a1395d00-bce3-11e9-92f7-50a6ad95ed16.png">

This was tested with a clean new account on inrupt.net.
I do see that inrupt.net is running on NSS 5.1.4, while the latest release is 5.1.6.
So perhaps this is already fixed here, but I could not find anything about this in the changelog.

**Comment by megoth** [comment]
This was a bug that happened because of a combination of bugs:

- The ACL functionality was looking for triples with `acl:defaultForNew` which has been made obsolete with `acl:default`
- A recursive function did not stop while trying to find a ACL resource connected to parent containers, and ended up doing a request to `https`

Both of these functions has been fixed in the latest dev-branches. We're about to merge these into master now, and updates should be pushed to inrupt.net and solid.community during the week. You can test this on dev.inrupt.net.

I'll close this issue for now, as it should be fixed in updates soon to come.

**Comment by rubensworks** [comment]
That's great, thanks!
