### ISSUE TITLE
.acl resource created with POST are created as .acl.ttl

### ISSUE THREAD

**Issue by bourgeoa** [solid/node-solid-server#1298]
since NSSv5.1.6 :  (if created with POST) .acl resources are created as .acl.ttl

Creation of resource using POST with a slug with extension (.meta, .acl, any file with extension - for exemple /foo.ttl are all created with a double extension : `.meta.ttl`,` .acl.ttl`, `foo.ttl.ttl`).
This is due to the fact that contentType is now mandatory.
In ldp.getAvailableUrl the `filename = slug +extension` should depend on the fact that slug as already an extension to avoid a double extension

PR #1282 fixes this issue in ldp.js
a test should be added to POST tests

**Comment by michielbdejong** [comment]
If the URL ends in `/.acl` and the content-type is `text/turtle`, then on disk you would expect to see a file named `.acl$.ttl`. The `$.ttl` is added to keep track of the fact that this resource was uploaded with content-type `text/turtle`. In a container listing, it should show up with its URL, which should never show the `$.ttl` suffix, that's only on disk.

This suffix has a $ and will not be added if the URL already ends in `.ttl`. So instead of:
.meta.ttl, .acl.ttl, foo.ttl.ttl
you would expect to see:
.meta$.ttl, .acl$.ttl, foo.ttl

This behaviour will not change in the switch to IPS, the mapping between URLs and filenames will keep the same mechanism.

**Comment by bourgeoa** [comment]
This mechanism is not working actually and my PR does not do that actually.
When I check the filesystem .acl URL are .acl file on disk. This change will need a migration

It has also implications on saving the data with solid-file-client on local filesystem or in memory

To better understand will the URL and file be  identical for all mime types (respectively foo.ttl or foo.html ...) ?

**Comment by bourgeoa** [comment]
> This suffix has a $ and will not be added if the URL already ends in .ttl. So instead of:
.meta.ttl, .acl.ttl, foo.ttl.ttl
you would expect to see:
.meta$.ttl, .acl$.ttl, foo.ttl

> This behaviour will not change in the switch to IPS, the mapping between URLs and filenames will keep the same mechanism.

NSS never used this behaviour, it keeps .acl and .meta files.
To do that resource-mapper.js as extended `mime-types`

>   L4 const { types, extensions } = require('mime-types')
     ...
     L27 overrideTypes = { acl: 'text/turtle', meta: 'text/turtle' }
     ...
     L34 this._types = { ...types , ...overrideTypes }

To use the new IPS behaviour I suppose it will imply a migration in the pod filesystem.

**Comment by jaxoncreed** [comment]
@bourgeoa @michielbdejong Is this an issue of spec ambiguity?

**Comment by bourgeoa** [comment]
I don't think it relates to spec ambiguity.
Fixed with #1282
