### ISSUE TITLE
[Proxy] it should use the ACL system to block access to the proxy URI.

### ISSUE THREAD

**Issue by deiu** [solid/node-solid-server#131]
Running a public proxy service is a bad thing -- it opens the door to DoS attacks. But on the other hand, it would be good if the ACL policy uses the Origin header. That way we can whitelist a given domain. (needs a discussion)

**Comment by nicola** [comment]
The server provider should be aware of this issue but we shouldn't solve this.

**Comment by kellyprankin** [comment]
Should this be closed?

**Comment by melvincarvalho** [comment]
@kellyprankin thanks for raising this

I think this relates to the --corsProxy option which has code at : 

https://github.com/solid/node-solid-server/blob/master/lib/handlers/cors-proxy.js

The reason is that some browsers incorrectly block calls to public resources due to CORS.  The workaround is to run a proxy on a pod.

But you dont want anyone to be able to use your proxy.  So it needs to be secured somehow.  At least, that's what I could understand from the issue.  I added the security tag to this.  But it only applies if you run a public proxy.

**Comment by RubenVerborgh** [comment]
Not a problem right now, can reconsider in the future.
