### ISSUE TITLE
Unclear how to determine a WebId from a POD

### ISSUE THREAD

**Issue by melvincarvalho** [solid/node-solid-server#1399]
Was discussing this with @angelo-v 

When going to the root of a pod `/`, in the current template the webid is written in plain text

However, it seems not obvious how to determine programmatically the WebId that owns a pod

Is there some pod specific metadata floating around, or could we come up for a design, if not?

**Comment by melvincarvalho** [comment]
Simple low tech solution:

Put the creator in `index.ttl`

**Comment by bourgeoa** [comment]
You can find it in https://yourPod/.meta

**Comment by melvincarvalho** [comment]
Great, thanks!

**Comment by kjetilk** [comment]
Ah, hold on, the .meta thing isn't necessarily what you should be looking at, the data in there is included with the container, so you should request `/` with `Accept: text/turtle`. 
Working out something consistent around this [has been tricky](https://github.com/solid/specification/issues/69), in the future, you'd get RDFa with it so that you can always get some RDF. :-)
