### ISSUE TITLE
It is easy for an application to get around the app permissions on a POD 

### ISSUE THREAD

**Issue by scenaristeur** [solid/node-solid-server#1424]
I think must be reported here A security question on the forum https://forum.solidproject.org/t/an-application-can-easily-get-around-apps-permissions/2946

Following our discussion here : User token and security - why SOLID server does not include the origin of the requester in token? 3

I have done some experiments and found the following :

It is easy for an application to get around the app permissions on a POD and execute actions that are not permitted by the POD owner. Here is to reproduce :

The user logs into the application (using solid.auth.client)
The user does not grant write permission to the application
The application gets the user session information, after login
The application requests an access token, with PoPToken.issueFor(…)
The application send this token to its server (http request to its server)
The server can now make http requests to the SOLID server, keeping origin == null
All permissions are granted, even if user did not give access to this app.
The way I did this is by changing a bit solid-auth-client.js this way :

Add to top of file :
import PoPToken from ‘@solid/oidc-rp/lib/PoPToken’

Add a new exported function :
async issueToken(input : any, session: webIdOidcSession) : Promise<?String> {
const popToken = PoPToken.issueFor(toUrlString(input), session)
return popToken;
}

And my js code of application :

let session = await solid.auth.currentSession();
let popupUri = ‘https://solid.community/common/popup.html’;
if (!session)
session = await solid.auth.popupLogin({ popupUri });
var token = await solid.auth.issueToken(session.webId, session);
// Now send this token to my server

**Comment by Vinnl** [comment]
Thanks for reporting this @scenaristeur. This is not an NSS-specific issue but relevant to Solid in general; as mentioned in the forum topic, there's now a FAQ entry relevant to this at https://solidproject.org/faqs#are-apps-vulnerable-to-an-origin-bypass

Since it's not specific to NSS, I suppose it's probably best to close this issue and, if so desired, people can discuss further on the forum? (Or potentially the Solid specification repo or the relevant Panels.)
