### ISSUE TITLE
Admin signup does not lead to a certificate stored in the browser

### ISSUE THREAD

**Issue by bshambaugh** [solid/node-solid-server#356]
There should be a certificate with a webid in it created with the admin signup stored in the browser. It may have worked in the past, but not now.  This is in the context of all exceptions and certificates for localhost previously removed.

To fix the problem temporarily I tried.
Trying openssl pkcs12 -export -out certificate.p12 -inkey localhost.key -in localhost.crt on
the key and cert created with
openssl genrsa 2048 > ../localhost.key
openssl req -new -x509 -nodes -sha256 -days 3650 -key ../localhost.key -subj '/CN=*.localhost' > ../localhost.crt

BUT This DOES NOT WORK

Logic pulled from conversation on linkeddata/gitter with melvin carvalho and dimitri z.  as well as the paper Using RDF Metadata to Enable Access Control on the Social Semantic Web section 2.3 (http://dig.csail.mit.edu/2009/Papers/ISWC/rdf-access-control/paper.pdf)

**Comment by nicola** [comment]
WebID+TLS is broken in modern browsers since they dropped keygen. We are working on a new auth scheme (mainly OpenID Connect), see work here: https://github.com/solid/node-solid-server/pull/330

Meanwhile, the key generation you are doing is for testing and those are certificates for running the server - not for the user. I would suggest you to wait for a couple of days, or instead, I would suggest you to use Firefox (?) which I guess it is the only browser working properly.

Thanks for reporting this.
I will close this ticket for now as what you describe it is a known bug being fixed.

Thanks a lot for your interest and patience, let me know if you want I can schedule a chat with you to get you started properly

**Comment by melvincarvalho** [comment]
@bshambaugh  @nicola I just tested keygen in firefox, and it appears to be working. \o/
