### ISSUE TITLE
Implement password recovery page

### ISSUE THREAD

**Issue by dmitrizagidulin** [solid/node-solid-server#389]
Especially important for users who don't have a password defined (legacy WebID-TLS users).
If user doesn't remember their password, or doesn't have one set, let them change it.

**Comment by ebporter** [comment]
Rather than full account recovery, we should just implement password recovery for the time being. The flow is as follows.

1. From any "Forgot password" link, you get to the "Send me a password recovery link" page with the following prompts:
"Enter your WebID (or Solid username)"
"Enter the email address with which you created this account"
2. This generates an email with the password recovery link for your WebID.
3. You click the link (or copy/paste the URL into your browser).
4. On the password recovery page, you are presented with a place to enter and then re-enter a new password, and then process the change.

The last step should trigger a notification by email and in the Solid notifications pane.

**Comment by dmitrizagidulin** [comment]
Implemented, closing.
