### ISSUE TITLE
support for multiple domain names

### ISSUE THREAD

**Issue by ghost** [solid/node-solid-server#401]
I haven't seen any notes about whether ubiquitous.databox.me / https://ubiquitous.databox2.com/ (or IP for that matter) may use a cname or something to point at say sailingdigital.com or s1.sailingdigital.com s2.sailingdigital.com 

Perhaps also a tool might be useful to easily enable that, which would include doing something with an SSL Cert i imagine at a minimum...? 

consideration is that the implications of managing the services may have a cost/benefit if someone was simply able to point their domain at it - rather than necessarily hosting/supporting the server.

**Comment by dmitrizagidulin** [comment]
@mediaprophet can you give a more detailed example of a use case?

**Comment by mediaprophet** [comment]
Yup.

I have ubiquitous.databox.com as a user, not operating a server.  I'd like
to mask the service-provider domain (databox.com) by pointing it at my
domain or my sub-domain.

So, I might use tim.wisdom.ai as an example.

This is the way most CDN's were pointed or indeed multi-site /
multi-network wordpress installs.  So, i'd have stream.streamingplatform.com
which was a cname for 22343492.CDN-company.com who provided the actual
service.

The way this would work would include the following functional aspects;

1. the ability for a user to enter the domain that they'd like to make
their account accessible.
2. the ability for the user to issue a cert.
2.1 could be generated using letsencrypt on the server-side.  usually this
would mean the user needs to prove they own the domain, mind, their are
needs on their side too...
2.2. alternative might be that user needs to upload cert. (2.1 is probably
preferred)

3. user needs to set-up NS records to have a CNAME record pointing at the
subdomain.

eg:
data.mywebsite.me
CNAME
myaccount.databox.me

user then has cert issued from databox that has a URI of
data.mywebsite.me/profile/card#me rather than the same @ databox.me

the purpose of this feature request would be to support uptake by users who
may wish to use their own domains / configure their own environments,
without necessarily storing/maintaining their own servers...

they can own their domain, and in-turn migrate their services to another
provider maintaining their URI's for so-long as they maintain their domain
registration.

**Comment by dmitrizagidulin** [comment]
Doesn't this seem a bit out of scope for this server repo? That is, accomplish-able via usual sysadmin skills (setting CNAME records, adjusting SSL certificates, etc)?

**Comment by mediaprophet** [comment]
The CNAME change is out of scope.  Account holder would need to know what
to do.  But the ability for the instance to issue a TLS certificate for a
seperate domain (inc. subdomain) would be part of the server instance, not
the client (cname changing) side.

This feature wouldn't be very useful for a single user on a server.  It
would makes a difference for a server that has a plurality of domains being
pointed at it / WebID-TLS certs being issued; vs. a singular provider.

I haven't put alot of time into looking at the code base for support for
this particular function and will have a better look into it, but i figured
some settings may be required within the server-side to allow creation of
the SSL cert and perhaps look at any security implications relating to a
user / web-traffic targeting a cname.

user experience may end-up with something that might fit into the
preferences (/settings) file / page...

not sure if that's out of scope or otherwise.  not my call.  just figured
it was useful.

have you got a domain? perhaps try pointing a subdomain cname at your
dataspace and see how easy it is to get it working ;)

if it's simply documentation - that's awesome.  I don't think that's the
case however...

I also noticed the recovery function had some issues:
https://github.com/solid/node-solid-server/issues/175

Perhaps the simple method is to fix that.

Mind; i was also being mindful of the difference between a wildcard cert.
and what can be done with lets encrypt.  If people BYOD (bring your own
domain) then perhaps their is a way to configure only using lets-encrypt,
which might lower cost and simplify set-up options.

**Comment by dmitrizagidulin** [comment]
@mediaprophet thanks!

**Comment by mediaprophet** [comment]
FYI:

thinking about it more, i'll also look into how to configure virtual hosts
in node.js so someone can host their entire domain off it; pointing
different directories at different cname records, then how to go about
permissions to allow somethings to be accessible without TLS at all (ie:
the www record) and others protected.

ie:
www.mydomain.com --> ubiquitous.databox.me/public/website
manage.mydomain.com --> ubiquitous.databox.me (warp or whatever)
rww.mydomain.com --> web 3.0 (solid) apps interface (for example).
etc..

may take a few days to review.

Tim.

**Comment by mediaprophet** [comment]
NOTE: where TLS noted above, the comment refers to WebID-TLS (as current pages often prompt for WebID-TLS cert) 

https://github.com/expressjs/vhost 
http://shamadeh.com/blog/web/nodejs/express/2014/07/20/ExpressMultipleSites.html

For pseudo-anon purposes; does it help to route via a TLD that is not assigned to the account holder?   is some means to obfuscate the parties, save query methods by server-admin's internally? 
Is IPFS potentially helpful in identifying an approach to do so? 
https://github.com/solid/node-solid-server/issues/429
