### ISSUE TITLE
Record the WebID of the user who created a resource

### ISSUE THREAD

**Issue by dmitrizagidulin** [solid/node-solid-server#407]
Add ability for the server to record / keep track of who created a resource (see parent issue https://github.com/solid/solid/issues/111). The server has that information at the time of resource creation (that is, by the time a PUT/POST/PATCH succeeds, the user has been authenticated, and their WebID is known to the server). 

The main design challenge is - where to store this creator WebID? There are two main options:
1. Store it in a resource's `.meta`. However, given the current way we handle `.meta` resources (that is, as just another resource), this would give the ability for anyone with write access to change or remove the creator's WebID. So in order for this option to be viable, we would have to change the semantics of `.meta` files so that only the server can update them. (We already do this with Containers -- a client simply passes additional triples they want associated with a container during the POST request, and the server automatically places those triples in the new container's `.meta`, and returns them in subsequent GET requests transparently.)
2. (Option recommended by @deiu) Store this resource metadata (the WebID of the creator) in a separate out-of-band place, such as a SQLite database.

**Comment by rhiaro** [comment]
Storing it in SQLite seems like a bit of a confession that this linked data stuff isn't really working doesn't it..? A triplestore would be great, but if we're going to use the file system for everything using `.meta` is fine.. but either way shouldn't we be storing this in RDF?

**Comment by csarven** [comment]
*This comment is intended to be a heads-up or a reminder. Not offering a solution, but with the hope that it will trigger a different way of looking at this problem and or reconsider what's actually desired.*

* Consider designing the simplest thing that could possibly work right now, and see how the rest of the system behaves. Is the solution something you want to use or is it just interesting to code?
* Don't make the data travel unless it is absolutely necessary. Acknowledge what that cost is and be prepared to deal with it.
* Don't introduce too many moving components. Something will at some point will fail or not behave within established parameters. That's a certainty. No one wants to maintain when things go wrong.
* Is the mechanism to "record / keep track of who created a resource" in *flow* with the rest of the design? If it requires an out of band workflow, are the limitations or potential pitfalls kept in the radar?
* Will the workflow of the chosen mechanism impose or influence the design of the rest of the system? If you want to get out of that workflow down the line, what might be the costs? Who will have to pay or address them?
* Is this intended to reinvent user accounts + file ownership/permissions in OS or something 'really' unsolved previously in the history of computing? [for some implementations of the Solid platform/service it may be sensible to map to accounts on the OS - granted this issue is for a particular implementation. This could give file ownership/permissions through the OS out of the box. Not to mention that it will be as fast as it gets. See if there is a middle-ground somewhere.]

**Comment by deiu** [comment]
In fact, it's really a matter of identifying how reusable that data is (i.e. is it going to be exported/imported somewhere else?). In any case, I have a feeling it will most likely be stored in an RDF store.

**Comment by csarven** [comment]
Looking at the proposed options:

Using a store forces a design towards two distinct data islands with separate software stack (which puts the burden on consuming software in the end). Imposes a massive dependency for the server to be functional (unless this is meant only as an extension/optional). One still has to address the discrepancies when the data moves around e.g., the names of the resources in static files use relative locations, with the idea that when they are eventually globally accessed, the data doesn't have to change. This is in contrast to the resources that live in the store which use absolute names. If the files move to a new server, the store has to be updated, reindexed, recached etc. Or any number of reasons where the resources in the store has the be synchronised with the resources in the filesystem. Maybe this is all 'fine', but compare that with:

.meta approach will be orders of magnitude faster and simpler to maintain because it integrates seamlessly with the existing workflow.

What's the simplest design to achieve what you want right now? What can .meta do that an RDF store can't and vice-versa for this particular use case? Do people that want to commit to node-solid-server want to commit to an RDF store just to more or less keep track of the creator of the resource? (I don't doubt that the RDF store can be utilised for more things down the line, but without that clearly identified, there is not much information to go on with. At that point, one would naturally ask: why bother with mutable files in the filesystem any way?)

**Comment by elf-pavlik** [comment]
#275 suggests resource linked with `rel="describedby"`(aka. .meta) for storing the content type of described resource, who created it could also stay stored in that meta resource.

**Comment by zoggy** [comment]
If I understand correctly https://www.w3.org/2005/Incubator/webid/spec/tls/#the-webid-authentication-protocol, several WebIds can be verified for the same connection, so the user can have several valid WebIds for the same request. How to choose which one is "the" WebId to keep as author of a resource ?

**Comment by dmitrizagidulin** [comment]
@zoggy That's very interesting, I didn't realize the webid-tls spec allowed for multiple WebIDs!

In practice, our reference servers only parse and verify a single WebID from a certificate. (I'm not sure what happens when there are multiple links encountered - maybe it picks the first one?)

(Fwiw, we're in the process of moving away from using WebID-TLS as primary authentication, and towards [WebID-OIDC](https://github.com/solid/solid/tree/master/proposals/webid-oidc)).

**Comment by zoggy** [comment]
Thanks. In this case I will also handle only the first verified WebId for my first tests, and switch to OIDC in the future.

**Comment by dmitrizagidulin** [comment]
@zoggy Sounds great!
