### ISSUE TITLE
If server has favico.ico at usual place it should be used rather than the solid icon.

### ISSUE THREAD

**Issue by timbl** [solid/node-solid-server#486]
The PR https://github.com/solid/node-solid-server/pull/481
breaks favico.ico on existing web sites which use the usual convention.
Please fix this to only supply a favicon if the user has not put one at the usual place.

**Comment by timbl** [comment]
(I also notice the default provided looks smaller than icons for other sites)

**Comment by dmitrizagidulin** [comment]
After investigation, I do not see a good way to detect a `favicon.ico` request, then check if an icon exists for that account, and if not invoke the `serve-favicon` npm lib.

So I think the best way to fix this issue is to remove the `serve-favicon` npm lib, and to create a default `favicon.ico` and the corresponding `favicon.ico.acl` during account creation (along with the other default folders & files). And then the user can delete it or upload a different one, as they like.

**Comment by dmitrizagidulin** [comment]
Fixed as of PR #492, closing.
