### ISSUE TITLE
Support content negotiation for error responses

### ISSUE THREAD

**Issue by dmitrizagidulin** [solid/node-solid-server#508]
Currently, node-solid-server only supports returning errors with `Content-Type: text/html`. 
Add support for some other error content types (based on the request `Accept:` header, etc).

1. Decide which error formats to support (JSON, Turtle?).
2. For Turtle errors, pick an appropriate error ontology
3. For JSON errors, pick appropriate format/RFC.

**Comment by timbl** [comment]
Well - the problem here is,  how do you know separately what formats the client can handle and would like for error messages, which are different from the original data?     For example, I may just want an image, any image, for this fetch, but b happy with any format for the error page,  or I may do a very open accept-anything fetch of data, but still only be able to cope with an HTML error page.

**Comment by timbl** [comment]
If we want to send data back with the error response, then I guess we could use RDF/a
