### ISSUE TITLE
Do not return User header for non-WebID TLS auth schemes

### ISSUE THREAD

**Issue by dmitrizagidulin** [solid/node-solid-server#523]

**Comment by melvincarvalho** [comment]
Out of curiosity.  Why would you not want to return a User header after autn?

**Comment by RubenVerborgh** [comment]
Because it would give any application access to the user ID. If I'm logged in to a Solid server, any webpage can see my user ID at the moment by accessing any resource from that Solid server.

**Comment by melvincarvalho** [comment]
Ah thanks.  FWIW some of the apps I had previously written have used the User header in order to personalize a page, e.g. to pull in someone's name, avatar and friends list, in a social setting.  It's a convenient way of allowing one click personalization, without having to type in a long string into a form, or query string, at least until browsers can provide such functionality via an API, which I think is being proposed.

I've not checked but this may possibly cause edge case bugs, in some of the older apps I've written.  But they are not really in use, so not a huge deal.

**Comment by RubenVerborgh** [comment]
@melvincarvalho I presume those apps use WebID+TLS? Or something else?

**Comment by melvincarvalho** [comment]
Yes, exactly.  So for example an app on github might use a user header from a public server.

So if you click the login button, and you're not logged in already, you'll get the user header after you send the cert.

But if you had been logged in and have a cookie you'd still get a user header back.  This change may change that behavior.

There are a couple of other fallbacks that I use, one is to check the query string for the user, which I think is a good pattern.  And another is to store the user (webid) in localstorage.

**Comment by RubenVerborgh** [comment]
> But if you had been logged in and have a cookie you'd still get a user header back. This change may change that behavior.

That's right. Note that the cookie-based authentication is unsafe and will be removed (#524).

**Comment by melvincarvalho** [comment]
Got it.  May I request that the version is bumped, after the hardening.  As it may be a breaking change.

**Comment by timbl** [comment]
"Because it would give any application access to the user ID. If I'm logged in to a Solid server, any webpage can see my user ID at the moment by accessing any resource from that Solid server."  -- are your sure the web page isn't blocked by CORS? Are you sure the User header isn't blocked?

**Comment by RubenVerborgh** [comment]
@timbl We're explicitly exposing the `User` header in https://github.com/solid/node-solid-server/blob/v4.0.14/lib/create-app.js#L30
