### ISSUE TITLE
Fix or replace directory browser

### ISSUE THREAD

**Issue by RubenVerborgh** [solid/node-solid-server#537]
The current Solid server integrates Warp, but Warp broke because of #526.

**Comment by RubenVerborgh** [comment]
Alternative: bundle Warp with node-solid-server.

**Comment by RubenVerborgh** [comment]
I just tried bundling Warp by placing it in the `common` folder, and that works fine.

The new plan of action is to include multiple apps into an `apps` folder on initialization (cloning them from GitHub). These apps could include Warp, mashlib, etc.

We would implement this as follows:
- in multi-user mode, place `apps` on the server's account
- in single-user mode, place `apps` on the user's account

This would require a modification to `server-config.js` with an extra `initializeApps` function, that is called from `ensureWelcomePage`.

**Comment by timbl** [comment]
I counter-propose using the full local databrowser instead of warp,
- as it gives much more functionality for all kinds of data
- it avoids the problem of the origin of the web app need ing to be 
I suggest an upgrade of the server pull in the latest mashlib.js and databrowser.html, but making sure that if the user has configured their server to use their own specific databrowser file, that config is not overwritten by the server upgrade.  

I suggest both the small HTML file and the large JS file are provided on the server.  An alternative would be for us to serve the JS file from a solid.github.io etc -- a place we control and upgrade.

**Comment by RubenVerborgh** [comment]
Another suggestion is to fix Warp (https://github.com/linkeddata/warp/issues/23).

**Comment by RubenVerborgh** [comment]
Regarding using the full databrowser, my two cents would be to not enable this by default, for the following reasons:
- I think it is more complicated to use than Warp, and might not be suitable for everybody.
- Since it feels more like a full application than Warp, it _might_ give people the impression that databrowser = Solid.

For the last point, a redirect to a public space (such as indeed solid.github.io) might change that impression for some users. This is also what currently happens with Warp.

**Comment by RubenVerborgh** [comment]
Proposal: use #567 (Data Browser).

**Comment by RubenVerborgh** [comment]
Data Browser proposal implemented in #573.
