### ISSUE TITLE
Registering a new account is disabled for the WebID-TLS

### ISSUE THREAD

**Issue by melvincarvalho** [solid/node-solid-server#631]
When starting up a server with auth="tls" the user is presented with two options

"Register" or "Login"

When clicking "Register" -- following message is displayed

> Registering a new account is disabled for the WebID-TLS

This is confusing to new developers and it would be helpful to change the message / workflow.

@dmitrizagidulin do you have any insight into the previous behavior, or desired behavior, here?

**Comment by melvincarvalho** [comment]
Possibly related : signup.html

https://github.com/solid/node-solid-server/blob/master/static/signup.html

**Comment by dmitrizagidulin** [comment]
I think the main idea was to prevent countless users trying to create an account and no cert being generated, and then being unable to log back in.

**Comment by melvincarvalho** [comment]
@dmitrizagidulin ah, got it!

So given that certs are working on firefox, I think we can try and detect the browser, then guide the user a bit better.

**Comment by sensespidey** [comment]
I've been working on a patchset that will allow auth=tls to be re-enabled by implementing client-side certificate generation using the [PKI.js](http://pkijs.org) library as wrapped by [enrollment-js](https://gitlab.com/authenticity/enrollment-js). I believe this could effectively replace the <keygen>/spkac approach in the code now, and allow for WebID-TLS registration across many/most browsers.

[this branch of node-solid-server](https://github.com/CityOfOsmio/node-solid-server/commits/re-enable-webid-tls-authn) has some initial commits toward working WebID-TLS registration/certificate generation, combined with my [experimental branch of enrollment-js](https://gitlab.com/authenticity/enrollment-js/commits/3-expose-keypair-generation-functions) which exposes a couple of functions to do key generation and certificate creation/self-signing.

This is all a little janky atm, and doesn't completely work, but I thought I'd post a progress report and maybe get some help debugging and polishing this patchset off :)

**To test:** It's probably easiest to start with a fresh clone of our forked node-solid-server branch linked above, as I've patched the register-form.hbs view template which gets copied into config/views when the server is first run. You'll also need to clone and checkout the experimental branch of enrollment-js, then run "npm build" on it to generate a patched copy of enrollment-2.0.4.min.js, then place this in the common/js folder so that it will get included in the Register page of the server.

**What to expect:** the patchset as it stands interrupts the regular POST to /api/accounts/new that should happen when the user hits Submit on the Register form, as I'm currently focusing only on trying to generate a working WebID-TLS certificate. Thus, no account is created on submission, and all that will happen is you get a new .p12 file downloaded when you hit submit. This is the result of the enrollment-js keygen() and generateAndSign() functions, combined with the embedded javascript in register-form.hbs, which is *nearly* working.

**What's broken:** the .p12 is not parsed successfully by OpenSSL, which complains that the private key is missing. I believe this happens because the [pkcs12.create()](https://github.com/CityOfOsmio/node-solid-server/blob/re-enable-webid-tls-authn/default-views/account/register-form.hbs#L165) function is not working as intended to create a proper .p12 bundle including both private key and certificate.

The other big issue that remains is the certificate itself, which is nothing like a WebID certificate at the moment- the generateAndSign() function is basically a stub right now, taken from an example in the PKI.js documentation. Nonetheless, I believe it should generate a parseable certificate, so the major blocker is the .p12 issue described above. If I can get past that, I'll fix the generation code to include a proper SAN and other relevant bits, as well as look at how to submit this certificate back to /api/accounts/new and create a user account with the full certificate in lieu of the spkac value previously used.

**Comment by RubenVerborgh** [comment]
We are deprecating WebID-TLS mode, so this will no longer be relevant.
