### ISSUE TITLE
Existing dashboards are not regenerated after dashboard improvements

### ISSUE THREAD

**Issue by melvincarvalho** [solid/node-solid-server#688]
After improvements to the dashboard existing users will still have the existing index.html.  And therefore, will not see the improvements leading to a possible inconsistent user experience.  

One possible solution would be to have a link or script to regenerate templates from the original.  Im sure there are other possible strategies.

Related issues : https://github.com/solid/node-solid-server/issues/683 , https://github.com/solid/node-solid-server/issues/683

**Comment by dmitrizagidulin** [comment]
Yeah, this is a tough one (though kind of necessary). We need to solve it on two levels:

1. Updating the New Account *template* (of the dashboard), so that new accounts created after a code update reflect the changes.
2. Updating each individual user's dashboard on existing accounts.

### Updating Templates
Part of the design assumption behind solid-server (which may need to be re-examined) is to make it easy for server operators to *customize* the look of the server -- what the site front page looks like, what each new created account looks like, etc. And so that these changes persist and are not overwritten by upstream code changes in the repo.

That's why node-solid-server has a two-layer sort of structure. The default templates (new account templates, email templates) are managed by the main repo, and live in `/default-templates` and `/default-views` directories. When a server is first started up, a *copy* of those templates is copied into `/config/templates` and `/config/views`, and those dirs are git-ignored. 
So, the contents of `/config/` are for installation-specific files (such as the templates), which the server operator can modify, and won't be over-written.

So, this solves the problem of individual modifications not being over-written by server updates. But of course it instead runs into the problem of - when there's upstream fixes on the server, how do those propagate into the installation-specific templates?

There's a couple of options that I can see.

**Option 1:** Don't offer server operators ability to customize templates (especially while solid-server is in rapid development), so that `/config/templates` are symlinked directly to `/default-templates`, so that they automatically get updated when upgrading to a new code version. Meaning, maybe it's too early to focus on customization.

**Option 2:** Do nothing - leave the system as is. And document (for server operators) that when updating code, if there's any template changes, operators will either need to delete the contents of their `/config` dirs (so they get re-created from new templates), or they need to apply those fixes manually to their customized templates.

**Option 3:** Add a config option (asked during the `solid init` step), asking whether the operator wants to have custom templates (in which case, they'll need to proceed as outlined in Option 2), or go with the default ones (in which case, they'll act as described in Option 1). I think each config option adds confusion, but this may be the easiest option.

### Updating Existing Accounts
Existing user accounts (created from account template) add another layer of complexity to this.

When a new account is created, its contents are copied from `/config/templates/new-account`. So that if upstream template changes are made on the server, and the contents of `/config` is regenerated, this won't affect existing users.

The only solution for this that I can think of is to create an external 'Check/Update Your Solid Account' app (hosted on github.io or something), that would be able to do things like create needed config options, index entries, refresh the account template (and specifically the account dashboard).

**Comment by megoth** [comment]
After discussing with @kjetilk and @justinwb I've decided to go with the approach that @RubenVerborgh suggested in https://github.com/solid/node-solid-server/issues/936. My PR will consist of the following:

* A script that updates index.html with the latest version if meta-tag is not set

This means that we need to give people good time to update their index.html the first time we enable this, and a good resource for how they can do it. I'm open to suggestions on how we should do this in general, but will coordinate with the people working on solid.community and inrupt.net for how we want to do it there.

**Comment by melvincarvalho** [comment]
thanks for looking at this & +1 from me wrt solid.community

**Comment by megoth** [comment]
As there is a PR merged for this (https://github.com/solid/node-solid-server/pull/953), I hope it's ok for me to close this issue.
