### ISSUE TITLE
 error: unknown option `--webid'

### ISSUE THREAD

**Issue by dr0i** [solid/node-solid-server#711]
In the part "Creating a certificate for local testing" of the  REAMDE it's said one should do:

$ solid --webid --port 8443 --cert ../localhost.cert --key ../localhost.key -v

But that results in

>  error: unknown option `--webid'

**Comment by dmitrizagidulin** [comment]
Hi @dr0i!

It’s looking for a command before the flags, so you want to add ‘start’ to that. so: ‘solid start —webid etc’.

Also, keep in mind that if you’re testing with localhost and self-signed certificates, you’ll wamt to use ‘solid-test start’ instead of solid. (that turns off rejecting of self-signed certs)

**Comment by dmitrizagidulin** [comment]
Thanks for filing the issue - yeah, it can probably be clearer. So that commandline example assumes that you’ve already generated a cert (via something like openssl)

**Comment by dmitrizagidulin** [comment]
@dr0i is it ok to close this issue?

**Comment by dr0i** [comment]
Sure - though why not clarify the README by merging #712 or otherwise?
