### ISSUE TITLE
Content views self-nesting with Internal Server Error 500 from Fetcher

### ISSUE THREAD

**Issue by Techokami** [solid/node-solid-server#811]
Hello, I recently got Solid running on my server so I could use it to have full control of my everything (e.g. The Whole Point), but it is not working properly. When I try to view any of my content, such as my profile card or my private inbox, it loads a frame that then loads itself a second time, and at the bottom of both is the following (censored) error message, this one from viewing the profile card:
```Outline.expand: Unable to fetch <https://[SOLID]:8443/profile/card>: Failed to load  <https://[SOLID]:8443/profile/card> Fetcher: <https://[SOLID]:8443/profile/card> Internal Server Error status: 500```
I have no idea why this is happening, and I am not seeing any errors in my regular log files. I tried this again with the server set to verbose output, and this gist contains the (censored) log output: https://gist.github.com/Techokami/ac978835eae65795441e10cc0bb56d7e

Now I did search the issues before making this one, and the only thing that looks remotely close to what I was getting is #653 which was resolved without really going into detail on *HOW* it was resolved. So I'm at a total loss here. It was kind of working, but then started doing this as soon as I tried to do anything useful in it, like set up my profile.

**Comment by newmedicine** [comment]
I have the same issue, running 4.1.6 using docker

**Comment by kjetilk** [comment]
Sorry for not getting back to you before!

It seems like there is something wrong with your certificates. I have two hunches, one is that you may have self-signed certificates, but you run it with the `solid` command line rather than the `solid-test` command line, the other is that there is something wrong with the actual certificate.

Anyway, you might want to ask in the forum, where have set it up for questions like these: https://forum.solidproject.org/

We'll close the issue for now, but please reopen if the problem persists.
