### ISSUE TITLE
Explain how username is leveraged on registration page

### ISSUE THREAD

**Issue by justinwb** [solid/node-solid-server#823]
We've received numerous reports of users not realizing that their username would be used publicly. It isn't obvious to them that it becomes the public sub-domain associated with their account, and forms the basis of their public webid. We need to provide a bit of explanation here, and I think we do it in two parts...

1. As users are typing in their username, have a bit of text updating as they type with:
Your public Solid POD URL will be: http://[username].hostname.com
Your public Solid WebID will be: https://[username].hostname.com/profile/card#me

2. Then provide a bit of explanation on what these things actually are...

(Something like... but feel free to tweak)

Your POD URL is like the homepage for your solid pod. By default, it is readable by the public, but you can always change that if you like by changing the access control.

Your Solid WebID is your globally unique identity that you can use to identify and authenticate yourself with other PODs across the world.

**Comment by kjetilk** [comment]
Right, but this isn't universally true, it is just for multi-user installs, so I think we should only display this message for multi-user installs.

**Comment by kjetilk** [comment]
Issues such as should also go in here: https://github.com/solid/solid/issues/205

**Comment by melvincarvalho** [comment]
Good point.  It's worth noting that nothing in solid says that anything in your pod needs to be public.  It's just the node solid server defaults.  We can explain this to users.  

The slight confusion occurs because registration does two things

- creates a pod and public folder
- creates a public webid for those that dont have one (99% of users)

Longer term when signup is an app, we'll have better ways to communicate these things, I suspect!

**Comment by kjetilk** [comment]
Not sure while this is still open, I think it is fixed and released, so probably I just forgot to close it.
