### ISSUE TITLE
Prefixes incomplete in turtle file added to the server

### ISSUE THREAD

**Issue by pheyvaer** [solid/node-solid-server#891]
I add the following Turtle to the server (via HTTP PUT) at the location `https://ph_test.solid.community/public/test.ttl`:

```
<https://ph_test.solid.community/public/test.ttl#something> a <http://schema.org/Thing>;
  <http://schema.org/test> <https://ph_test.solid.community/profile/card#me>;
  <http://schema.org/test2> <https://ph2.solid.community/profile/card#me>.
```

However, when I do HTTP GET of `https://ph_test.solid.community/public/test.ttl#something` I get:

```
@prefix : <#>.
@prefix schema: <http://schema.org/>.
@prefix c: </profile/card#>.
@prefix c0: <https://ph2.solid.community/profile/card#>.

:something
    a schema:Thing.
:something schema:test c:me.
:something schema:test2 c0:me.
```

The problems are that I do not have the full URL of `:something` as the prefix has only `#` and the prefix `c` does not have the full IRI as the hostname is missing. Is it possible to get the full IRIs in the prefixes?

**Comment by kjetilk** [comment]
Actually, these are [relative URIs](https://tools.ietf.org/html/rfc3986#page-26), and the resolution is done by the parser, or somewhere in the app code. Usually, you will end up setting it relative to the URI of the document. In your case, following the algorithm in RFC3986, the URI of `:something` would be `https://ph_test.solid.community/public/test.ttl#something`.

This is actually pretty useful, because it allows you to write Turtle before you know the full URI of the resource that you're writing. You can do the same thing in HTML documents.

Nevertheless, since I think one man's confusion is an opportunity to improve the developer experience, what we should look into is the tool support that helps setting the base URI, if that's clear enough.

**Comment by pheyvaer** [comment]
> Actually, these are [relative URIs](https://tools.ietf.org/html/rfc3986#page-26), and the resolution is done by the parser, or somewhere in the app code. Usually, you will end up setting it relative to the URI of the document. In your case, following the algorithm in RFC3986, the URI of `:something` would be `https://ph_test.solid.community/public/test.ttl#something`.

I was thinking that it was something like that, but I was confused about paths starting with `#` and `/`, but got it working now (see below).

> This is actually pretty useful, because it allows you to write Turtle before you know the full URI of the resource that you're writing. You can do the same thing in HTML documents.

Cool! Hadn't thought about it like that :smile: 

> Nevertheless, since I think one man's confusion is an opportunity to improve the developer experience, what we should look into is the tool support that helps setting the base URI, if that's clear enough.

At the moment I do the GET and parse the file with the [`N3.Parser`](https://github.com/rdfjs/N3.js#parsing) to which I provide the baseIRI.

**Comment by kjetilk** [comment]
Right! I think we could make the Turtle a bit more human friendly too! :-)

**Comment by pheyvaer** [comment]
Nice! :smile: Thanks for the clarifications.
