### ISSUE TITLE
Watch changes in folder via WebSockets

### ISSUE THREAD

**Issue by pheyvaer** [solid/node-solid-server#933]
When using websockets on a folder, I don't get `pub` messages when a file is added to that folder. However, it would nice to have such a feature. For example, to detect if new notifications arrive in the inbox of a user.

**Comment by aorumbayev** [comment]
@megoth I was wondering if there are any updates on this issue. 
Is there an implementation roadmap somewhere with approximate release dates for this feature to be implemented ?
Would be happy to try to contribute 🙂

**Comment by michielbdejong** [comment]
This discussion was continued and then paused again at https://github.com/solid/solid-spec/issues/180

**Comment by csarven** [comment]
When a new resource is added to a container, the container's description is updated to include a statement about the contained resource (eg. ldp:contains). Triggering a notification when a subscribed resource changes is expected.

Although this issue is currently labelled as a feature, the current NSS behaviour can alternatively be considered a bug :)

More details (initial proposal): https://github.com/solid/specification/issues/51#issuecomment-609708197
