### ISSUE TITLE
Test LegacyResourceMapper in production

### ISSUE THREAD

**Issue by RubenVerborgh** [solid/node-solid-server#947]

**Comment by melvincarvalho** [comment]
Could you define production in this context?  I suspect to use inrupt.net makes to here, as it has guaranteed commercial backing.

Re solid.community we are running 4.2.0 right now, the goal is to move to 4.4.0 in order to benefit from quotas, I guess around early December.  Quite a lot of commits tho between those 2 versions.

If 4.4.0 is running well, the next goal will be to go for 5.0.0 possibly in december or early 2019.

**Comment by RubenVerborgh** [comment]
I actually think we skipped this step, right @rubensworks, so we might close this?

**Comment by rubensworks** [comment]
Yes indeed, we can directly test the new ResourceMapper (#950). I'll upgrade the dev server with the newly released beta later today.

**Comment by melvincarvalho** [comment]
@rubensworks which is the dev server?  

We run one at : https://solidtest.space/

**Comment by rubensworks** [comment]
https://dev.inrupt.net/

We'll update that one with the new beta first, we'll migrate the rest once 5.0.0 is out of beta.
