### ISSUE TITLE
Use of acl:accessTo in inherited ACLs

### ISSUE THREAD

**Issue by kjetilk** [solid/node-solid-server#963]
What seems to be our final main hurdle to `acl-check.js` integration #777 was encountered late tonight, when we found the tests for auth-proxy, it contains an [inherited ACL](https://github.com/solid/node-solid-server/blob/master/test/resources/auth-proxy/.acl) that contains `acl:accessTo` statements about resources further out in the path, e.g.:

```turtle
[
  a acl:Authorization;
  acl:accessTo </server/a/>;
  acl:agent <https://ruben.verborgh.org/profile/#me>;
  acl:mode acl:Read, acl:Write, acl:Control
].

[
  a acl:Authorization;
  acl:accessTo </server/a/r>;
  acl:agent <https://ruben.verborgh.org/profile/#me>;
  acl:mode acl:Read
].
```

I can certainly see the argument for having that possibility, but we had problems because `acl-check.js` distinguishes between `acl:accessTo` and `acl:default` based on `directory` parameter, and we couldn't easily tell how to use it with the current code. Much tearing of hair and grinding of teeth ensued. :-)

Then, this seems to be  [outside of the spec](https://github.com/solid/web-access-control-spec#acl-inheritance-algorithm-example), where only `acl:default` is used in inherited ACLs.

Can we safely assume that `acl:accessTo` is not supported in inherited ACLs? 

Apart from a few smaller things, this seems to be the main issue holding 5.0.0 back now.

**Comment by RubenVerborgh** [comment]
Hmm, there was actually a good reason for this deep ACL.

The reason is that this is used in a proxy context, i.e., the mapped `/server/a/r` is not a real folder on the server, but rather a resource `/a/r` on `/server` (which is not necessarily a Solid server but can be any Web server).

Both @timbl and I use it to control access to a proxied resource.

It's probably not in the spec indeed, but it is a current use case. I'm fine with temporarily breaking it for v5 though.

**Comment by kjetilk** [comment]
Yeah, I can certainly see the use for it. I also put some [failing tests in](https://github.com/solid/node-solid-server/commit/4f47123a4fcdc6d82bd1ebc1eb8c2ef750144c4f) to track it, but it seems like a pretty significant hurdle that could delay us quite a bit, and I'm really anxious to not delay it any further.

Great if we could have a decision about this before tomorrow.

**Comment by timbl** [comment]
- Do I assume that the ACL file in your example is the one for `/server/a/`? 
- Do I assume that the request in question is about  access to `/server/a/r` ? 
- Do I assume that there is no `/server/a/r.acl` ?

So the ACL file you show is the the ACL file which is relevant.
And it gives access to the resource in question.  So I think the query in acl-check will succeed, won't it?

You don't say above what happens, or what you expect to happen, or what you think should happen

- The code does NOT allow the access
- You found a test which expects that it does
- 
In favor of this -- it is mathematically reasonable to be able to put the auth for a deep resource in the higher level acl, and the query is simple, the code should be easy.     t is useful where you have a proxy t

Against it - we don't have UI code to be able to handle this.   The UI to be able to do this
  The UI gives you access to either  a direct ACL file about the resource or the inherited acl file.  Not clear how the UI would look.     Do you then allow the top level directory to even give a default setting for an interneditiate one  ??  I think not as then the search becomes much more complicated. but that would be symmetrical in this case.

I'm thinking that this use should not be allowed.
It should be called out in the spec that it is not.

We need to write the ACL spec as a mathematical function so that it is absolutely clear what we meant.

**Comment by RubenVerborgh** [comment]
> I'm thinking that this use should not be allowed.

All fine with me (even though I like it).

I just want to point to https://github.com/solid/node-solid-server/issues/595 was a feature request of yours, and we created this functionality for that together. Is it no longer a requirement, or do you want to solve this differently?

**Comment by kjetilk** [comment]
My concern right now is 5.0.0, and not delaying that any further, we should seek to freeze that today so that we can focus on the road ahead, and I see this as something that needs further specification and implementation that isn't something we can do today.

We can always come back to it post-5.0.0. So, are we OK on not having it in 5.0.0?

**Comment by kjetilk** [comment]
Resolved on gitter. Skipping tests and closing.
