### ISSUE TITLE
Missing Terms & Conditions checkbox

### ISSUE THREAD

**Issue by rubensworks** [solid/node-solid-server#982]
When Terms & Conditions for a server is enabled, no checkbox for this is present during registration.

As such, registration always fails with the error:

> Accepting Terms & Conditions is required for this service

**Comment by megoth** [comment]
I was unable to reproduce this. Will work with @rubensworks to figure out what differs from our setups.

**Comment by rubensworks** [comment]
Ah, it's possible I was using an old config folder with templates though.

But I think we should have an (automatic) migration for this though? Or should these also use the new meta tag?

**Comment by megoth** [comment]
We could have `npm run clean` as part of a migrate-script, but we don't have a generic migrate-script yet, right? You're suggesting that we should have a migrate-script? (I agree to this in general, I think; just need to be careful how we set it up so that it will work with all possible migrations.)

The only file that needs the new meta tag (you're thinking of `solid-allow-automatic-updates`, right?) is the `index.html` in accounts. This meta tag is already inserted in `default-templates/new-account/index.html`, which adds it to new accounts.

**Comment by rubensworks** [comment]
> We could have npm run clean as part of a migrate-script, but we don't have a generic migrate-script yet, right? You're suggesting that we should have a migrate-script?

Indeed, I think it would be a good idea to think about this.
Maybe it would make sense to start using `solid-allow-automatic-updates` in the (HTML) files in `config/` as well for situations like these?

This should probably be a different issue though, and I guess this one can be closed then?

**Comment by megoth** [comment]
Yes, I agree ^_^
